apiVersion: apps/v1
kind: Deployment
metadata:
  name: underthedome-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: underthedome-operator
  template:
    metadata:
      labels:
        name: underthedome-operator
    spec:
      serviceAccountName: underthedomeoperator
      containers:
        - name: underthedome-operator
          # Replace this with the built image name
          image: 172.30.1.1:5000/underthedome/underthedome-operator:v0.0.1
          command:
          - underThedome-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              value: prova
            - name: OPERATOR_NAME
              value: "underThedome-operator"
